"use client"

import { useState } from "react"
import { useGame } from "@/lib/game/store"
import { GEAR_CLASSES, ITEM_MAP, PILOT_PROFILES } from "@/lib/game/data"
import { computeStats, baseStatsAtLevel, xpForLevel } from "@/lib/game/engine"
import { Button } from "@/components/ui/button"
import { Panel } from "./shared"
import { Brain, Crosshair, Gauge, Shield, Sparkles, Target, UserRound, Plane, Check, RefreshCw, Lock, Zap } from "lucide-react"
import { cn } from "@/lib/utils"
import type { EquipSlot, PilotStatKey, StatKey } from "@/lib/game/types"

const STAT_META: Record<PilotStatKey, { label: string; icon: typeof Crosshair }> = { attack: { label: "ATK", icon: Crosshair }, defense: { label: "DEF", icon: Shield }, agility: { label: "AGI", icon: Gauge }, shield: { label: "SHIELD", icon: Sparkles }, vision: { label: "VISION", icon: Target } }
const PILOT_SKILL_VALUES: Record<PilotStatKey, string> = { attack: "+30 ATK / điểm", defense: "+10 DEF / điểm", agility: "+10 ATK +5 DEF / điểm", shield: "+200 HP shield / điểm", vision: "+10 ATK +5 DEF / điểm" }
const SLOT_META: { slot: EquipSlot; label: string }[] = [{ slot: "weapon", label: "Vũ khí chính" }, { slot: "missile", label: "Tên lửa" }, { slot: "armor", label: "Giáp" }, { slot: "engine", label: "Động cơ" }, { slot: "shield", label: "Khiên" }]
const SKILL_CONVERSION: Record<string, string> = { "fire-shot": "Mỗi cấp: +4% ATK vũ khí thường", "missile-shot": "Mỗi cấp: +4% ATK tên lửa", concentration: "Mỗi cấp: +3 VISION và độ chính xác", "evasion-up": "Mỗi cấp: +3 EVA", "defense-up": "Mỗi cấp: +3% DEF" }

function numberForStat(stat: StatKey, aircraft: ReturnType<typeof computeStats> | null) {
  if (!aircraft) return 0
  return aircraft[stat]
}

export function PilotPanel() {
  const { state, dispatch } = useGame()
  const [selectorOpen, setSelectorOpen] = useState(false)
  const [previewId, setPreviewId] = useState<string>(PILOT_PROFILES[0].id)
  const pilot = state.pilot
  const profile = PILOT_PROFILES.find((p) => p.id === pilot.profileId)
  const preview = PILOT_PROFILES.find((p) => p.id === previewId) ?? PILOT_PROFILES[0]
  const aircraft = state.gears.find((g) => g.uid === pilot.aircraftUid) ?? state.gears[0]
  const aircraftStats = aircraft ? computeStats(aircraft, state.inventory) : null
  const aircraftBase = aircraft ? baseStatsAtLevel(aircraft.cls, aircraft.level) : null
  const locked = pilot.hasSelectedPilot && state.day - pilot.selectedAtDay < 10
  const selectPilot = () => { dispatch({ type: "SELECT_PILOT", profileId: preview.id }); setSelectorOpen(false) }
  const activeProfile = profile ?? preview
  const colors: Record<string, string> = { hp: "#fb5b60", attack: "#f5c451", defense: "#55d6be", speed: "#55b6ff", evasion: "#c18cff", energy: "#7ee787" }
  const statRows: { key: StatKey; label: string }[] = [{ key: "hp", label: "HP" }, { key: "attack", label: "ATK" }, { key: "defense", label: "DEF" }, { key: "speed", label: "SPD" }, { key: "evasion", label: "EVA" }, { key: "energy", label: "EN" }]

  return <div className="space-y-4">
    <div className={cn("flex items-center justify-between border p-3", pilot.hasSelectedPilot ? "border-primary/30 bg-primary/5" : "border-yellow-400/50 bg-yellow-400/10")}>
      <div><div className="font-display text-sm font-bold uppercase tracking-wider">{pilot.hasSelectedPilot ? <>Phi công liên kết: <span className="text-primary">{activeProfile.name} · {activeProfile.gear}-GEAR</span></> : <span className="text-yellow-300">Chưa chọn phi công</span>}</div><div className="text-[10px] text-muted-foreground">{pilot.hasSelectedPilot ? "Phi cơ gắn liền, thay phi công mở lại sau 10 ngày." : "Ngày 1 là bước khởi tạo. Chọn một phi công để kích hoạt phi cơ và kỹ năng ACE."}</div></div>
      <Button onClick={() => { setPreviewId(profile?.id ?? PILOT_PROFILES[0].id); setSelectorOpen(true) }} disabled={locked} className="gap-2 text-xs">{locked ? <Lock className="size-3.5" /> : <UserRound className="size-3.5" />} {locked ? `Khóa ${10 - (state.day - pilot.selectedAtDay)} ngày` : pilot.hasSelectedPilot ? "Đổi phi công" : "Chọn phi công"}</Button>
    </div>

    {selectorOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/80 p-4 backdrop-blur-sm"><div className="w-full max-w-5xl border border-primary/40 bg-panel p-4 shadow-2xl"><div className="mb-3 flex items-center justify-between"><div><div className="font-display text-lg font-bold text-primary">CHỌN PHI CÔNG / GEAR</div><div className="text-[10px] text-muted-foreground">Sau khi xác nhận, lựa chọn khóa 10 ngày. Mỗi phi công giữ riêng level, skill và trang bị.</div></div><Button variant="ghost" size="sm" onClick={() => setSelectorOpen(false)}>Đóng</Button></div><div className="grid gap-4 lg:grid-cols-[1fr_1.2fr]">
      <div className="space-y-2">{PILOT_PROFILES.map((p) => <button key={p.id} type="button" onClick={() => setPreviewId(p.id)} className={cn("flex w-full items-center gap-3 border p-2 text-left", preview.id === p.id ? "border-primary bg-primary/10" : "border-border/50 bg-card/40")}><img src={p.avatar} alt={`Chân dung ${p.name}`} className="size-16 object-cover"/><div className="flex-1"><div className="font-display font-bold">{p.name} <span className="text-xs text-primary">{p.gear}-GEAR</span></div><div className="text-[10px] text-muted-foreground">{p.specialty} · {p.aircraftName}</div></div>{p.id === pilot.profileId && <Check className="size-4 text-accent"/>}</button>)}</div>
      <div className="border border-border/60 bg-card/40 p-3"><div className="flex gap-4"><img src={preview.avatar} alt={`Chân dung ${preview.name}`} className="h-44 w-32 object-cover border border-primary/50"/><div><div className="font-display text-xl font-bold text-primary">{preview.name} · {preview.gear}-GEAR</div><div className="mt-1 text-xs text-muted-foreground">{preview.gender} · {preview.age} tuổi · {preview.specialty}</div><p className="mt-3 text-sm">{preview.description}</p><div className="mt-3 font-display text-xs font-bold uppercase text-yellow-300">TRAIL SKILL</div>{preview.trail.map((t) => <div key={t} className="mt-1 text-xs text-yellow-200">◆ {t}</div>)}</div></div><div className="mt-4 grid grid-cols-5 gap-2">{(Object.keys(STAT_META) as PilotStatKey[]).map((key) => <div key={key} className="border border-border/50 p-2 text-center"><div className="font-mono text-lg font-bold text-white">{preview.baseStats[key]}</div><div className="text-[9px] text-muted-foreground">{STAT_META[key].label}</div></div>)}</div><Button className="mt-4 w-full" onClick={selectPilot} disabled={locked || preview.id === pilot.profileId}><Check className="size-4"/> {preview.id === pilot.profileId ? "Đang sử dụng" : "Xác nhận chọn phi công"}</Button></div>
    </div></div></div>}

    <div className="grid gap-4 xl:grid-cols-[380px_1fr]"><Panel title="Thông tin nhân vật" icon={<Brain className="size-4" />} action={<span className="font-mono text-[10px] text-accent">LV {pilot.level} · {pilot.xp} XP</span>}><div className="flex gap-4">{profile ? <img src={profile.avatar} alt={`Chân dung ${profile.name}`} className="h-40 w-32 object-cover border border-primary/50"/> : <div className="flex h-40 w-32 items-center justify-center border border-dashed border-yellow-400/50 text-center text-xs text-muted-foreground">Chọn phi công</div>}<div className="min-w-0"><div className="font-display text-lg font-bold text-primary">{profile?.name ?? "Chưa chọn"}{profile && ` · ${profile.gear}-GEAR`}</div><p className="mt-1 text-xs text-muted-foreground">{profile?.description ?? "Hãy chọn một phi công để mở khóa phi cơ cá nhân."}</p>{profile && <div className="mt-3 space-y-1 text-xs">{profile.trail.map((t) => <div key={t} className="text-yellow-300">◆ {t}</div>)}</div>}<div className="mt-3 h-1.5 bg-secondary"><div className="h-full bg-accent" style={{ width: `${Math.min(100, pilot.xp / Math.max(1, xpForLevel(pilot.level)) * 100)}%` }}/></div><div className="mt-1 text-[10px] text-muted-foreground">EXP đến cấp tiếp: {Math.max(0, xpForLevel(pilot.level) - pilot.xp)}</div></div></div></Panel>
      <Panel title="TỔNG HỢP CHỈ SỐ CUỐI" icon={<Target className="size-4" />}><div className="mb-3 text-[10px] text-muted-foreground">Trắng = nhân vật · Xanh = phi cơ/trang bị · Tím = skill · Vàng = trail · Tổng = giá trị cuối.</div><div className="grid grid-cols-2 gap-2 sm:grid-cols-5">{(Object.keys(STAT_META) as PilotStatKey[]).map((key) => { const Icon = STAT_META[key].icon; const white = pilot.hasSelectedPilot ? pilot.stats[key] : 0; const blue = key === "attack" ? Math.round((aircraftStats?.attack ?? 0) / 30) : key === "defense" ? Math.round((aircraftStats?.defense ?? 0) / 10) : key === "shield" ? Math.round((aircraftStats?.hp ?? 0) / 200) : Math.round((aircraftStats?.speed ?? 0) / 10); const purple = pilot.skills.filter((s) => s.category === "common" && s.level > 1).reduce((n, s) => n + s.level, 0); const gold = profile ? Math.round(profile.baseStats[key] * .1) : 0; return <div key={key} className="border border-border/50 bg-card/40 p-2"><div className="flex items-center gap-1"><Icon className="size-3.5 text-primary"/><span className="font-display text-xs font-bold">{STAT_META[key].label}</span><b className="ml-auto text-lg text-white">{white + blue + purple + gold}</b></div><div className="mt-2 font-mono text-[10px]"><span className="text-white">{white} nhân vật</span><br/><span className="text-sky-400">+{blue} phi cơ/đồ</span><br/><span className="text-violet-400">+{purple} skill</span><br/><span className="text-yellow-400">+{gold} trail</span></div></div>})}</div></Panel>
    </div>

    <div className="grid gap-4 xl:grid-cols-2"><Panel title="Kỹ năng nhân vật" icon={<Sparkles className="size-4" />} action={<span className="text-[10px] text-accent">{pilot.skillPoints} điểm còn lại</span>}><div className="grid gap-2 sm:grid-cols-2">{(Object.keys(STAT_META) as PilotStatKey[]).map((key) => <div key={key} className="flex items-center justify-between border border-border/50 p-2"><div><div className="font-display text-xs font-bold">Skill {STAT_META[key].label}</div><div className="text-[10px] text-muted-foreground">{PILOT_SKILL_VALUES[key]}</div></div><Button size="xs" variant="secondary" disabled={!pilot.hasSelectedPilot || !pilot.skillPoints} onClick={() => dispatch({ type: "ALLOCATE_PILOT_STAT", stat: key })}>+1</Button></div>)}</div></Panel><Panel title={`Kỹ năng ACE · ${profile?.gear ?? "-"}-GEAR`} icon={<Zap className="size-4" />}><div className="grid gap-2">{pilot.skills.filter((s) => s.category === "gear").map((skill) => <div key={skill.id} className="border border-primary/30 bg-primary/5 p-2"><div className="flex items-center justify-between"><div className="font-display text-xs font-bold">{skill.name}</div><Button size="xs" variant="secondary" disabled={!pilot.skillPoints || skill.level >= skill.maxLevel} onClick={() => dispatch({ type: "UPGRADE_PILOT_SKILL", skillId: skill.id })}>Cấp {skill.level} · +1</Button></div><div className="mt-1 text-[10px] text-muted-foreground">{skill.desc}</div><div className="mt-1 text-[10px] text-cyan-300">{SKILL_CONVERSION[skill.id] ?? `${skill.effect} → quy đổi vào chỉ số Gear tương ứng`}</div></div>)}</div></Panel></div>

    <Panel title={`Phi cơ cá nhân · ${aircraft?.name ?? ""}`} icon={<Plane className="size-4"/>} action={<Button size="sm" variant="outline" disabled={!aircraft} onClick={() => aircraft && dispatch({ type: "REPAIR_GEAR", uid: aircraft.uid })}><RefreshCw className="size-3"/> Sửa chữa</Button>}><div className="grid gap-4 lg:grid-cols-[250px_1fr]"> <div className="border border-primary/30 bg-primary/5 p-3"><div className="font-display text-3xl font-bold text-primary">{aircraft?.cls ?? "-"}-GEAR</div><div className="mt-2 text-xs text-muted-foreground">LV {aircraft?.level ?? 1} · {aircraft?.xp ?? 0} XP</div><div className="mt-2 text-[10px] text-muted-foreground">HP {aircraft?.hpCurrent ?? 0} / {aircraftStats?.hp ?? 0}</div><div className="mt-1 h-1.5 bg-secondary"><div className="h-full bg-primary" style={{width: `${aircraftStats ? Math.min(100, aircraft.hpCurrent / Math.max(1, aircraftStats.hp) * 100) : 0}%`}}/></div><div className="mt-4 space-y-2">{statRows.map(({ key, label }) => <div key={key}><div className="flex justify-between text-[10px]"><span>{label}</span><b>{numberForStat(key, aircraftStats)}</b></div><div className="mt-1 h-1.5 bg-secondary"><div className="h-full" style={{ width: `${Math.min(100, numberForStat(key, aircraftStats) / 500 * 100)}%`, backgroundColor: colors[key] }}/></div></div>)}</div></div><div><div className="mb-2 text-xs font-bold uppercase tracking-wider text-primary">Tổng chỉ số phi cơ · base + item + trail</div><div className="mb-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{statRows.map(({ key, label }) => <div key={key} className="border border-border/50 bg-card/40 p-2"><div className="text-[9px] text-muted-foreground">{label}</div><div className="font-mono text-xl font-bold text-white">{numberForStat(key, aircraftStats)}</div><div className="text-[9px] text-cyan-300">gốc {aircraftBase?.[key] ?? 0} · đồ +{Math.max(0, (aircraftStats?.[key] ?? 0) - (aircraftBase?.[key] ?? 0))}</div></div>)}</div><div className="grid gap-2 sm:grid-cols-2">{SLOT_META.map(({ slot, label }) => { const equipped = aircraft?.equipped[slot]; const options = state.inventory.filter((i) => ITEM_MAP[i.defId]?.slot === slot); return <label key={slot} className="border border-border/50 bg-card/40 p-2"><span className="text-[9px] uppercase text-muted-foreground">{label}</span><select className="mt-1 w-full border border-border bg-secondary p-2 text-xs" value={equipped ?? ""} disabled={!aircraft} onChange={(e) => { if (aircraft && e.target.value) dispatch({ type: "EQUIP_ITEM", gearUid: aircraft.uid, itemUid: e.target.value }) }}><option value="">-- Chưa lắp --</option>{options.map((i) => <option key={i.uid} value={i.uid}>{ITEM_MAP[i.defId]?.name} +{i.level}</option>)}</select>{equipped && <button type="button" className="mt-1 text-[10px] text-rose-300" onClick={() => aircraft && dispatch({ type: "UNEQUIP_SLOT", gearUid: aircraft.uid, slot })}>Tháo trang bị</button>}</label>})}</div></div></div></Panel>
  </div>
}

export default PilotPanel
