import type {
  BuildingDef,
  BuildingKey,
  GearClass,
  GearClassDef,
  ItemDef,
  Sector,
} from "./types"

export const GEAR_CLASSES: Record<GearClass, GearClassDef> = {
  A: {
    cls: "A",
    name: "A-Gear",
    role: "Attacker",
    color: "var(--color-gear-a)",
    tagline: "Cận chiến áp sát, sát thương bùng nổ",
    base: { hp: 1400, attack: 210, defense: 120, speed: 95, evasion: 22, energy: 80 },
    growth: { hp: 140, attack: 26, defense: 12, speed: 4, evasion: 1.5, energy: 6 },
    strengths: ["DPS đơn mục tiêu cao nhất", "Áp sát nhanh", "Chí mạng mạnh"],
    buildCost: { credits: 1200, alloy: 400, energy: 120 },
  },
  B: {
    cls: "B",
    name: "B-Gear",
    role: "Bomber",
    color: "var(--color-gear-b)",
    tagline: "Oanh tạc diện rộng, phá công trình",
    base: { hp: 2200, attack: 180, defense: 180, speed: 55, evasion: 8, energy: 100 },
    growth: { hp: 240, attack: 22, defense: 20, speed: 2, evasion: 0.4, energy: 8 },
    strengths: ["Máu trâu nhất", "Sát thương diện rộng", "Công phá căn cứ"],
    buildCost: { credits: 1500, alloy: 620, energy: 100 },
  },
  I: {
    cls: "I",
    name: "I-Gear",
    role: "Interceptor",
    color: "var(--color-gear-i)",
    tagline: "Đánh chặn cơ động, né tránh cao",
    base: { hp: 1150, attack: 165, defense: 95, speed: 130, evasion: 40, energy: 90 },
    growth: { hp: 110, attack: 20, defense: 9, speed: 6, evasion: 2.4, energy: 7 },
    strengths: ["Tốc độ & né cao nhất", "Đánh chặn tàu mẹ", "Ra đòn trước"],
    buildCost: { credits: 1300, alloy: 360, energy: 150 },
  },
  M: {
    cls: "M",
    name: "M-Gear",
    role: "Magician / Support",
    color: "var(--color-gear-m)",
    tagline: "Hỗ trợ, hồi phục và buff hạm đội",
    base: { hp: 1300, attack: 130, defense: 110, speed: 80, evasion: 18, energy: 160 },
    growth: { hp: 120, attack: 14, defense: 11, speed: 3, evasion: 1.2, energy: 14 },
    strengths: ["Hồi máu hạm đội mỗi vòng", "Buff sát thương", "Năng lượng dồi dào"],
    buildCost: { credits: 1400, alloy: 300, energy: 200 },
  },
}

export const GEAR_ORDER: GearClass[] = ["A", "B", "I", "M"]

export const ITEM_DEFS: ItemDef[] = [
  // Weapons
  {
    id: "w_pulse",
    name: "Pulse Cannon",
    slot: "weapon",
    rarity: "common",
    bonus: { attack: 45 },
    cost: { credits: 500, alloy: 120 },
    desc: "Pháo xung cơ bản, ổn định.",
  },
  {
    id: "w_rail",
    name: "Rail Driver",
    slot: "weapon",
    rarity: "rare",
    bonus: { attack: 95, evasion: -4 },
    cost: { credits: 1400, alloy: 320, crystal: 20 },
    desc: "Pháo ray xuyên giáp, sát thương cao.",
  },
  {
    id: "w_plasma",
    name: "Plasma Lance",
    slot: "weapon",
    rarity: "epic",
    bonus: { attack: 165, energy: 20 },
    cost: { credits: 3200, alloy: 620, crystal: 60 },
    desc: "Thương plasma nung chảy giáp địch.",
  },
  {
    id: "w_singularity",
    name: "Singularity Core",
    slot: "weapon",
    rarity: "legendary",
    bonus: { attack: 260, speed: 10 },
    cost: { credits: 7200, alloy: 1200, crystal: 180 },
    desc: "Vũ khí kỳ dị, sát thương hủy diệt.",
  },
  // Missiles
  {
    id: "m_swarm",
    name: "Swarm Pods",
    slot: "missile",
    rarity: "rare",
    bonus: { attack: 60, speed: 6 },
    cost: { credits: 1100, alloy: 240 },
    desc: "Dàn tên lửa bầy đàn, đánh diện rộng.",
  },
  {
    id: "m_nova",
    name: "Nova Torpedo",
    slot: "missile",
    rarity: "epic",
    bonus: { attack: 120, defense: -10 },
    cost: { credits: 2800, alloy: 480, crystal: 45 },
    desc: "Ngư lôi Nova công phá công trình mạnh.",
  },
  // Armor
  {
    id: "a_plate",
    name: "Titan Plating",
    slot: "armor",
    rarity: "common",
    bonus: { hp: 300, defense: 30 },
    cost: { credits: 480, alloy: 200 },
    desc: "Giáp titan tiêu chuẩn.",
  },
  {
    id: "a_reactive",
    name: "Reactive Armor",
    slot: "armor",
    rarity: "rare",
    bonus: { hp: 550, defense: 70, speed: -5 },
    cost: { credits: 1600, alloy: 460, crystal: 25 },
    desc: "Giáp phản ứng nổ, giảm sát thương lớn.",
  },
  {
    id: "a_nanoweave",
    name: "Nanoweave Hull",
    slot: "armor",
    rarity: "epic",
    bonus: { hp: 900, defense: 120 },
    cost: { credits: 3400, alloy: 780, crystal: 70 },
    desc: "Vỏ nano tự tái tạo, cực bền.",
  },
  // Engine
  {
    id: "e_ion",
    name: "Ion Thruster",
    slot: "engine",
    rarity: "common",
    bonus: { speed: 20, evasion: 5 },
    cost: { credits: 520, alloy: 90 },
    desc: "Động cơ ion tăng tốc độ.",
  },
  {
    id: "e_warp",
    name: "Warp Drive",
    slot: "engine",
    rarity: "epic",
    bonus: { speed: 55, evasion: 18 },
    cost: { credits: 3000, alloy: 520, crystal: 55 },
    desc: "Động cơ warp, cơ động vượt trội.",
  },
  // Shield
  {
    id: "s_deflector",
    name: "Deflector Field",
    slot: "shield",
    rarity: "rare",
    bonus: { hp: 400, evasion: 10 },
    cost: { credits: 1300, alloy: 280, crystal: 30 },
    desc: "Khiên lệch hướng, tăng né.",
  },
  {
    id: "s_aegis",
    name: "Aegis Barrier",
    slot: "shield",
    rarity: "legendary",
    bonus: { hp: 750, defense: 90, evasion: 14 },
    cost: { credits: 6800, alloy: 1000, crystal: 160 },
    desc: "Khiên Aegis huyền thoại, phòng thủ tối thượng.",
  },
]

export const ITEM_MAP: Record<string, ItemDef> = Object.fromEntries(
  ITEM_DEFS.map((d) => [d.id, d]),
)

export const BUILDING_DEFS: Record<BuildingKey, BuildingDef> = {
  command: {
    key: "command",
    name: "Sở Chỉ Huy",
    desc: "Trung tâm căn cứ. Nâng cấp để mở khóa cấp công trình khác.",
    effect: "+ giới hạn cấp công trình, + uy tín",
    maxLevel: 10,
    baseCost: { credits: 2000, alloy: 600, crystal: 40 },
    costScale: 1.8,
  },
  hangar: {
    key: "hangar",
    name: "Nhà Chứa (Hangar)",
    desc: "Sửa chữa và bảo dưỡng phi thuyền. Tăng tốc độ hồi phục.",
    effect: "+ hồi durability mỗi ngày, + số Gear tối đa",
    maxLevel: 10,
    baseCost: { credits: 1200, alloy: 400 },
    costScale: 1.6,
  },
  factory: {
    key: "factory",
    name: "Nhà Máy Vũ Khí",
    desc: "Chế tạo vũ khí, trang bị. Giảm chi phí sản xuất.",
    effect: "- chi phí chế tạo trang bị",
    maxLevel: 10,
    baseCost: { credits: 1400, alloy: 500, crystal: 20 },
    costScale: 1.6,
  },
  reactor: {
    key: "reactor",
    name: "Lò Phản Ứng",
    desc: "Sản xuất năng lượng mỗi ngày cho căn cứ.",
    effect: "+ Năng lượng / ngày",
    maxLevel: 12,
    baseCost: { credits: 900, alloy: 260 },
    costScale: 1.5,
  },
  refinery: {
    key: "refinery",
    name: "Xưởng Luyện Kim",
    desc: "Khai thác & tinh luyện hợp kim mỗi ngày.",
    effect: "+ Hợp kim / ngày",
    maxLevel: 12,
    baseCost: { credits: 900, alloy: 200 },
    costScale: 1.5,
  },
  barracks: {
    key: "barracks",
    name: "Doanh Trại",
    desc: "Tăng giới hạn quân số cho hạm đội viễn chinh.",
    effect: "+ giới hạn quân số",
    maxLevel: 10,
    baseCost: { credits: 1100, alloy: 340 },
    costScale: 1.55,
  },
  turret: {
    key: "turret",
    name: "Tháp Phòng Thủ",
    desc: "Phòng thủ căn cứ trước phản kích của địch.",
    effect: "+ phòng thủ căn cứ",
    maxLevel: 10,
    baseCost: { credits: 800, alloy: 420, crystal: 15 },
    costScale: 1.5,
  },
  shipyard: {
    key: "shipyard",
    name: "Xưởng Đóng Tàu",
    desc: "Đóng phi thuyền mới nhanh & rẻ hơn.",
    effect: "- chi phí đóng Gear, + Gear tối đa",
    maxLevel: 10,
    baseCost: { credits: 1600, alloy: 560, crystal: 30 },
    costScale: 1.7,
  },
}

export const BUILDING_ORDER: BuildingKey[] = [
  "command",
  "hangar",
  "shipyard",
  "factory",
  "reactor",
  "refinery",
  "barracks",
  "turret",
]

export const SECTORS: Sector[] = [
  {
    id: "s1",
    name: "Vành Đai Helios",
    kind: "outpost",
    x: 22,
    y: 68,
    threat: 320,
    garrison: 40,
    reward: { credits: 900, alloy: 260, energy: 120 },
    troopReward: 30,
    captured: false,
    recommendedPower: 1800,
    faction: "Cướp Biển Vũ Trụ",
  },
  {
    id: "s2",
    name: "Trạm Khai Mỏ K-7",
    kind: "outpost",
    x: 40,
    y: 78,
    threat: 520,
    garrison: 60,
    reward: { credits: 1400, alloy: 520, crystal: 30 },
    troopReward: 45,
    captured: false,
    recommendedPower: 3200,
    faction: "Liên Minh Bion",
  },
  {
    id: "s3",
    name: "Pháo Đài Nebula",
    kind: "base",
    x: 58,
    y: 60,
    threat: 980,
    garrison: 120,
    reward: { credits: 3000, alloy: 900, crystal: 90, energy: 300 },
    troopReward: 90,
    captured: false,
    recommendedPower: 6500,
    faction: "Liên Minh Bion",
  },
  {
    id: "s4",
    name: "Cổng Không Gian Zeta",
    kind: "outpost",
    x: 35,
    y: 42,
    threat: 720,
    garrison: 80,
    reward: { credits: 1900, alloy: 640, crystal: 50 },
    troopReward: 60,
    captured: false,
    recommendedPower: 4400,
    faction: "Cướp Biển Vũ Trụ",
  },
  {
    id: "s5",
    name: "Căn Cứ Vệ Tinh Orion",
    kind: "base",
    x: 70,
    y: 40,
    threat: 1500,
    garrison: 160,
    reward: { credits: 4800, alloy: 1400, crystal: 140, energy: 500 },
    troopReward: 130,
    captured: false,
    recommendedPower: 9500,
    faction: "Đế Chế Arclight",
  },
  {
    id: "s6",
    name: "Vùng Tối Cygnus",
    kind: "outpost",
    x: 82,
    y: 62,
    threat: 1150,
    garrison: 110,
    reward: { credits: 3400, alloy: 1000, crystal: 100 },
    troopReward: 95,
    captured: false,
    recommendedPower: 7600,
    faction: "Đế Chế Arclight",
  },
  {
    id: "s7",
    name: "Tàu Mẹ ARCLIGHT PRIME",
    kind: "mothership",
    x: 84,
    y: 22,
    threat: 3200,
    garrison: 300,
    reward: { credits: 12000, alloy: 3200, crystal: 400, energy: 1500 },
    troopReward: 250,
    captured: false,
    recommendedPower: 18000,
    faction: "Đế Chế Arclight",
  },
]

export const STARTING_GEAR_NAMES = ["Vanguard", "Aegis", "Falcon", "Oracle"]
